# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-react-app  # 👉 indique où sont tes fichiers npm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # 1️⃣ Récupération du code
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Installation des dépendances (plus rapide que npm install)
      - name: Installer les dépendances
        run: npm ci

      # 4️⃣ Lancer les tests Vitest
      - name: Lancer les tests unitaires
        run: npm run test -- --run

      # 5️⃣ Construire le projet (build)
      - name: Build du projet
        run: npm run build

      # 6️⃣ Sauvegarder le build (utile pour un job de déploiement)
      - name: Archiver le dossier dist
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist
